// LWX Pong — a tiny CC0 NES game for LibretroWebXR test content.
//
// Single screen, NROM (mapper 0). Left paddle = player 1 (D-pad up/down on the
// NES controller, which the WebXR frontend's RetroPad maps to). Right paddle =
// a simple CPU that tracks the ball UNTIL player 2 presses up/down, after which
// player 2 drives it (so it doubles as a 2-player multiplayer test: in a shared
// room the client's forwarded P2 input reaches the host core as controller 1).
// Score shown as stacked blocks on each side.
//
// All hardware/timing code lives in the frozen neslib boilerplate (crt0.s,
// neslib.sinc, ...). This file is just game logic calling neslib's documented
// API — the AI-friendly split the research recommends. CC0.

#include "neslib.h"

typedef unsigned char u8;
typedef signed char   s8;
typedef unsigned int  u16;

// Required by the vendored display.sinc (it references a C-side zeropage byte).
#pragma bss-name (push,"ZEROPAGE")
#pragma data-name (push,"ZEROPAGE")
u8 oam_off;
#pragma data-name(pop)
#pragma bss-name (pop)

// Play-field bounds (pixels). Ball/paddle tiles are 8x8.
#define TOP     16          // top wall (ball top min)
#define BOT     208         // ball top max (ball bottom = 216)
#define PADBOT  184         // paddle top max (paddle is 24 tall -> 208)
#define LX      16          // left paddle x
#define RX      232         // right paddle x
#define PADH    24          // paddle height

// One solid tile (#1) is the only art we need; CHR is generated by the build.
// Sprite palette 0, colour 1 = white; BG palette 0, colour 1 = grey (net).
static const u8 PALETTE[32] = {
  0x0f,0x10,0x00,0x00, 0x0f,0x10,0x00,0x00, 0x0f,0x10,0x00,0x00, 0x0f,0x10,0x00,0x00,
  0x0f,0x30,0x00,0x00, 0x0f,0x30,0x00,0x00, 0x0f,0x30,0x00,0x00, 0x0f,0x30,0x00,0x00,
};

static u8  lpY, rpY;        // paddle top y
static u8  bx, by;          // ball top-left
static s8  dx, dy;          // ball velocity
static u8  lScore, rScore;
static u8  pad, pad2, i, spr;
static u8  p2_active;       // latches once player 2 first touches up/down

static void draw_net(void) {
  // Dashed centre line in the background — drawn once while rendering is off.
  for (i = 0; i < 30; i += 2) {
    vram_adr(NTADR_A(16, i));
    vram_put(1);
  }
}

static void serve(s8 dir) {
  bx = 124; by = 116;
  dx = dir;                 // toward the player who was just scored on
  dy = (rand8() & 1) ? 1 : -1;
}

static void reset_round(void) {
  ppu_off();
  pal_all(PALETTE);
  vram_adr(NAMETABLE_A);
  vram_fill(0, 32 * 30);    // blank the whole nametable (tile 0)
  vram_fill(0, 64);         // attribute table -> palette 0
  draw_net();
  ppu_on_all();
}

void main(void) {
  lpY = 92; rpY = 92;
  lScore = 0; rScore = 0;
  p2_active = 0;
  reset_round();
  serve(-2);

  while (1) {
    ppu_wait_nmi();
    pad  = pad_poll(0);
    pad2 = pad_poll(1);

    // --- player 1 paddle (left) ---
    if ((pad & PAD_UP)   && lpY > TOP)    lpY -= 2;
    if ((pad & PAD_DOWN) && lpY < PADBOT) lpY += 2;

    // --- right paddle: player 2 once they join, else CPU ---
    if (pad2 & (PAD_UP | PAD_DOWN)) p2_active = 1;
    if (p2_active) {
      // human player 2 (matches P1 speed)
      if ((pad2 & PAD_UP)   && rpY > TOP)    rpY -= 2;
      if ((pad2 & PAD_DOWN) && rpY < PADBOT) rpY += 2;
    } else {
      // CPU, slower than the ball so it can miss
      if (rpY + 12 > by + 4) { if (rpY > TOP)    rpY -= 1; }
      else                   { if (rpY < PADBOT) rpY += 1; }
    }

    // --- ball movement ---
    bx += dx;
    by += dy;

    // top / bottom walls
    if (by < TOP)      { by = TOP; dy = -dy; }
    else if (by > BOT) { by = BOT; dy = -dy; }

    // left paddle
    if (dx < 0 && bx <= LX + 8 && bx >= LX) {
      if (by + 8 > lpY && by < lpY + PADH) { bx = LX + 8; dx = -dx; }
    }
    // right paddle
    if (dx > 0 && bx + 8 >= RX && bx <= RX) {
      if (by + 8 > rpY && by < rpY + PADH) { bx = RX - 8; dx = -dx; }
    }

    // scoring (a paddle missed)
    if (bx < 8)        { if (rScore < 9) ++rScore; serve(2);  }
    else if (bx > 248) { if (lScore < 9) ++lScore; serve(-2); }

    // --- render sprites (tile 1 = solid block) ---
    spr = 0;
    spr = oam_spr(LX, lpY,      1, 0, spr);
    spr = oam_spr(LX, lpY + 8,  1, 0, spr);
    spr = oam_spr(LX, lpY + 16, 1, 0, spr);
    spr = oam_spr(RX, rpY,      1, 0, spr);
    spr = oam_spr(RX, rpY + 8,  1, 0, spr);
    spr = oam_spr(RX, rpY + 16, 1, 0, spr);
    spr = oam_spr(bx, by,       1, 0, spr);
    for (i = 0; i < lScore; ++i) spr = oam_spr(4,   24 + i * 10, 1, 0, spr);
    for (i = 0; i < rScore; ++i) spr = oam_spr(248, 24 + i * 10, 1, 0, spr);
    oam_hide_rest(spr);
  }
}
