// LWX Zap Gallery — a CC0 NES light-gun shooting gallery for LibretroWebXR.
//
// A real little game for the NES Zapper (and thus the WebXR light-gun prop):
// a white bullseye target pops up at random spots on a dark field. Aim with the
// gun and pull the trigger — if the muzzle is over the target the photodiode
// senses its bright pixels (a HIT, +1 and a faster next target); fire at the
// dark field, or let the per-target timer run out, and it's a MISS. Three misses
// ends the game. Shoot to start / retry.
//
// CO-OP (2 players). The gallery now supports two players in two ways, picked
// once from the title screen and designed to work in BOTH input regimes:
//
//   * 1P (Zapper, port 2): the original single-gun game, unchanged.
//   * 2P SHARE (alternating turns) — shippable TODAY on the single shipped
//     Zapper: P1 shoots a wave of targets, then P2 shoots a wave, alternating,
//     each with their own score and miss count; the game ends when BOTH players
//     have used up their misses, and the higher score wins. Needs no second gun
//     and no core changes — one Zapper, taken in turns.
//   * 2P DUEL (simultaneous) — the target experience once the per-port
//     "multiport" light-gun core lands: P2 keeps the Zapper on port 2 (port-2
//     photodiode + trigger), and P1 fires with a controller/second gun routed to
//     PORT 1 (read via pad_trigger(0), the A button = fire). Both players' shots
//     are resolved every frame against the shared light sense (each gun aims the
//     photodiode on its own read once multiport is active), with independent
//     scores. Auto-armed: if a port-1 fire is ever seen the game flips into DUEL
//     so a second gun "just works" without a menu dance.
//
// How the Zapper is read — the part that has to be exactly right:
// the Zapper reports two bits on the port-2 register $4017 — D3 = light sense and
// D4 = trigger. CRUCIALLY D3 is REAL-HARDWARE polarity: D3 = 0 when the photodiode
// senses a bright pixel under the muzzle, D3 = 1 when it sees no light. And the
// photodiode only sees that pixel during the brief window the BEAM scans it — so a
// read only catches the light if it happens while the beam is on the muzzle's
// scanline. We must therefore spin-read $4017 ACROSS THE WHOLE VISIBLE FRAME (not
// just during vblank) so one read coincides with the beam crossing the target, and
// latch "light seen" = any read with D3 clear. (A short poll right after the NMI —
// i.e. in vblank — never overlaps the visible scanout and so never sees light; that
// was the bug.) Because the only bright thing on the field is the target, a latched
// light at trigger time means the muzzle was on the target.
//
// Built with cc65 + Shiru's neslib (the frozen boilerplate in this dir). The CHR
// (font + target tiles) is generated by scripts/make-nes-gallery.mjs. CC0.

#include "neslib.h"

typedef unsigned char u8;
typedef unsigned int  u16;

// Port-2 controller/Zapper register. D3 = light sense (0 = light detected, 1 = no
// light — real-HW polarity), D4 = trigger (1 = held).
#define CTRL_PORT2 (*(volatile u8*)0x4017)

// $4017 reads to spin across one visible frame (~29780 CPU cycles / ~25-cycle
// read loop ≈ 1200; 1500 gives margin so the beam-on-target window is always
// caught). The loop deliberately runs past vblank into the active picture.
#define POLL_READS 1500

// display.sinc (vendored) references this C-side zeropage byte by name.
#pragma bss-name (push,"ZEROPAGE")
#pragma data-name (push,"ZEROPAGE")
u8 oam_off;
#pragma data-name(pop)
#pragma bss-name (pop)

// --- tile ids (must match scripts/make-nes-gallery.mjs) ----------------------
#define T_BLANK 0          // transparent / black field
#define T_WHITE 1          // solid white (unused directly, handy bright tile)
// 2..5 = the 16x16 target metasprite (TL,TR,BL,BR)
#define T_DIGIT 16         // tiles 16..25 = '0'..'9'
#define T_ALPHA 32         // tiles 32..57 = 'A'..'Z'

// --- game tuning -------------------------------------------------------------
#define MAX_MISS   3
#define START_TIME 150     // frames a target stays before timing out (~2.5s)
#define MIN_TIME   54       // fastest target lifetime as you score
#define TIME_STEP  4        // shave this many frames off per hit
#define WAVE_LEN   5        // shots per turn in SHARE (alternating) mode

// state machine
#define ST_TITLE 0
#define ST_PLAY  1
#define ST_OVER  2

// co-op mode (chosen at the title, then fixed for the game)
#define MODE_SOLO  0       // 1 player, Zapper only
#define MODE_SHARE 1       // 2 players, alternating turns on one Zapper
#define MODE_DUEL  2       // 2 players, simultaneous (P1=port1 fire, P2=Zapper)

// bg palette 0: black backdrop, white, blue, red. spr palette 0: same family,
// target is white (1) with a red (2) bullseye centre.
static const u8 PALETTE[32] = {
  0x0f,0x30,0x21,0x16,  0x0f,0x30,0x21,0x16,  0x0f,0x30,0x21,0x16,  0x0f,0x30,0x21,0x16,
  0x0f,0x30,0x16,0x21,  0x0f,0x30,0x16,0x21,  0x0f,0x30,0x16,0x21,  0x0f,0x30,0x16,0x21,
};

// 16x16 target: four sprites (xoff,yoff,tile,attr); x=128 terminates. The attr
// byte (palette select) is patched per-player at draw time so each player's
// turn/target reads in their colour family.
static u8 target_meta[] = {
  0,0, 2, 0,
  8,0, 3, 0,
  0,8, 4, 0,
  8,8, 5, 0,
  128
};

static u8  state;
static u8  mode;            // MODE_SOLO / MODE_SHARE / MODE_DUEL
static u8  tx, ty;          // target top-left (pixels)
static u8  light, z, sid;
static u8  trig2, trig2Prev;   // port-2 Zapper trigger (P2 in duel / shared gun)
static u8  pad1, pad1Trig;     // port-1 controller (P1 in duel; menu nav)
static u8  cur;             // whose turn / who just fired this frame: 0=P1, 1=P2
static u16 score0, score1; // per-player score
static u8  miss0,  miss1;  // per-player misses
static u8  done0,  done1;  // 1 once that player has hit MAX_MISS (SHARE mode)
static u8  t_timer;         // frames until the current target times out
static u8  cur_time;        // current target lifetime (shrinks as you score)
static u8  wave;            // shots remaining in the current SHARE turn
static u16 frame;           // free-running, used to seed the RNG on first shot
static u16 pr;              // $4017 spin-read counter (spans a visible frame)
static u8  vbuf[24];        // HUD vram-update buffer (two scores + miss digits)

// ASCII -> tile id ('0'..'9', 'A'..'Z', else blank).
static u8 chr_of(u8 c) {
  if (c >= '0' && c <= '9') return T_DIGIT + (c - '0');
  if (c >= 'A' && c <= 'Z') return T_ALPHA + (c - 'A');
  return T_BLANK;
}

// Write a string to nametable A at (x,y). Rendering must be OFF.
static void put_str(u8 x, u8 y, const char *s) {
  vram_adr(NAMETABLE_A | (((u16)y << 5) | x));
  while (*s) { vram_put(chr_of(*s)); ++s; }
}

// Write a 4-digit number at (x,y). Rendering must be OFF.
static void put_num4(u8 x, u8 y, u16 v) {
  u8 d0, d1, d2, d3;
  d3 = T_DIGIT + (v % 10); v /= 10;
  d2 = T_DIGIT + (v % 10); v /= 10;
  d1 = T_DIGIT + (v % 10); v /= 10;
  d0 = T_DIGIT + (v % 10);
  vram_adr(NAMETABLE_A | (((u16)y << 5) | x));
  vram_put(d0); vram_put(d1); vram_put(d2); vram_put(d3);
}

// Clear nametable A to the field tile and reset its attributes to palette 0.
static void clear_screen(void) {
  vram_adr(NAMETABLE_A);
  vram_fill(T_BLANK, 32 * 30);
  vram_adr(0x23c0);
  vram_fill(0, 64);
}

// Pack a 4-digit score + 1 miss digit into the vbuf at byte offset `o`, written
// to the nametable run starting at vram address ($20<<8 | adrLo). Returns the
// next free byte offset. The two players' HUD blocks are stacked this way.
static u8 hud_block(u8 o, u8 adrLo, u16 sc, u8 ms) {
  vbuf[o + 0] = 0x20 | NT_UPD_HORZ; vbuf[o + 1] = adrLo; vbuf[o + 2] = 5;
  vbuf[o + 6] = T_DIGIT + (sc % 10); sc /= 10;
  vbuf[o + 5] = T_DIGIT + (sc % 10); sc /= 10;
  vbuf[o + 4] = T_DIGIT + (sc % 10); sc /= 10;
  vbuf[o + 3] = T_DIGIT + (sc % 10);
  vbuf[o + 7] = T_DIGIT + ms;        // miss digit tacked onto the same run
  return o + 8;
}

// Rebuild the live HUD buffer. SOLO: one score + miss at row 1 (as before).
// 2P: P1 block at NTADR_A(3,1)=$2023 and P2 block at NTADR_A(20,1)=$2034, so
// "P1 nnnn m" sits left and "P2 nnnn m" right. set_vram_update consumes vbuf.
static void update_hud(void) {
  u8 o;
  if (mode == MODE_SOLO) {
    // Score digits at NTADR_A(8,1)=$2028, miss digit at NTADR_A(28,1)=$203c.
    vbuf[0] = 0x20 | NT_UPD_HORZ; vbuf[1] = 0x28; vbuf[2] = 4;
    { u16 s = score0;
      vbuf[6] = T_DIGIT + (s % 10); s /= 10;
      vbuf[5] = T_DIGIT + (s % 10); s /= 10;
      vbuf[4] = T_DIGIT + (s % 10); s /= 10;
      vbuf[3] = T_DIGIT + (s % 10); }
    vbuf[7] = 0x20 | NT_UPD_HORZ; vbuf[8] = 0x3c; vbuf[9] = 1;
    vbuf[10] = T_DIGIT + miss0;
    vbuf[11] = NT_UPD_EOF;
    return;
  }
  o = hud_block(0,  0x26, score0, miss0);   // $2026 = NTADR_A(6,1)
  o = hud_block(o,  0x34, score1, miss1);   // $2034 = NTADR_A(20,1)
  vbuf[o] = NT_UPD_EOF;
}

// Move the target to a fresh random spot, clear of the HUD row.
static void relocate(void) {
  tx = 16 + (rand8() % 208);   // 16..223  (16px wide target stays on screen)
  ty = 48 + (rand8() % 144);   // 48..191  (below the HUD)
}

static void enter_title(void) {
  ppu_off();
  set_vram_update(NULL);
  clear_screen();
  put_str(9,  4, "LWX ZAP GALLERY");
  put_str(8,  9, "SHOOT THE TARGETS");
  put_str(5, 11, "AIM WITH THE LIGHT GUN");
  put_str(8, 16, "SHOOT  START 1P");
  put_str(8, 18, "START  2P SHARED GUN");
  put_str(4, 21, "2ND GUN ON PORT 1 2P DUEL");
  ppu_on_all();
}

static void enter_play(void) {
  ppu_off();
  clear_screen();
  if (mode == MODE_SOLO) {
    put_str(2, 1, "SCORE");
    put_str(23, 1, "MISS");
  } else {
    // Two HUD labels: P1 left, P2 right, each "Pn ____ _".
    put_str(3, 1, "P1");
    put_str(17, 1, "P2");
  }
  update_hud();
  set_vram_update(vbuf);
  ppu_on_all();
}

// Compose the GAME OVER / RESULT screen. SOLO shows one score; 2P shows both
// plus the winner (or a tie).
static void enter_over(void) {
  ppu_off();
  set_vram_update(NULL);
  clear_screen();
  put_str(11, 8, "GAME OVER");
  if (mode == MODE_SOLO) {
    put_str(11, 12, "SCORE");
    put_num4(17, 12, score0);
  } else {
    put_str(9, 12, "P1");
    put_num4(13, 12, score0);
    put_str(9, 14, "P2");
    put_num4(13, 14, score1);
    if      (score0 > score1) put_str(10, 17, "P1 WINS");
    else if (score1 > score0) put_str(10, 17, "P2 WINS");
    else                      put_str(11, 17, "A TIE");
  }
  put_str(9, 21, "SHOOT TO RETRY");
  ppu_on_all();
}

static void start_game(void) {
  set_rand(frame ? frame : 1);   // entropy from how long the title was up
  score0 = 0; score1 = 0;
  miss0 = 0;  miss1 = 0;
  done0 = 0;  done1 = 0;
  cur_time = START_TIME;
  cur = 0;                  // P1 goes first (in SOLO, P1 is the only player)
  wave = WAVE_LEN;
  enter_play();
  relocate();
  t_timer = cur_time;
  state = ST_PLAY;
}

// In SHARE mode, hand the gun to the next player who still has misses left, and
// reset the wave. Called when a turn's wave is used up or the active player is
// out. Returns 1 if a live player took the turn, 0 if the game is over.
static u8 pass_turn(void) {
  done0 = (miss0 >= MAX_MISS);
  done1 = (miss1 >= MAX_MISS);
  if (done0 && done1) return 0;
  // alternate; skip a finished player
  cur ^= 1;
  if (cur == 0 && done0) cur = 1;
  if (cur == 1 && done1) cur = 0;
  wave = WAVE_LEN;
  return 1;
}

// Award a hit to player `p` (0 or 1) and advance the field.
static void do_hit(u8 p) {
  if (p == 0) { if (score0 < 9999) ++score0; }
  else        { if (score1 < 9999) ++score1; }
  if (cur_time > MIN_TIME) cur_time -= TIME_STEP;
  relocate();
  t_timer = cur_time;
  update_hud();
}

// Charge a miss to player `p`. In SHARE mode a player who reaches MAX_MISS is
// "out" and the game ends only when both are out; in SOLO/DUEL the first to
// MAX_MISS ends it.
static void do_miss(u8 p) {
  if (p == 0) ++miss0; else ++miss1;
  relocate();
  t_timer = cur_time;
  update_hud();

  if (mode == MODE_SHARE) {
    if (((p == 0) ? miss0 : miss1) >= MAX_MISS) {
      if (!pass_turn()) { enter_over(); state = ST_OVER; }
    }
    return;
  }
  // SOLO / DUEL: any player reaching the cap ends the game.
  if (miss0 >= MAX_MISS || miss1 >= MAX_MISS) { enter_over(); state = ST_OVER; }
}

void main(void) {
  ppu_off();
  pal_all(PALETTE);
  oam_clear();
  state = ST_TITLE;
  mode  = MODE_SOLO;
  enter_title();
  trig2Prev = 0;
  frame = 0;

  while (1) {
    // Wait for vblank: this DMAs the OAM we built last iteration and applies the
    // HUD vram update, so the target now visible matches what we sense below.
    ppu_wait_nmi();
    ++frame;

    // Read PORT 1 (standard controller / second gun routed there by the multiport
    // core). pad_trigger latches button-down edges; A = fire. Used as P1's fire in
    // DUEL and to pick a 2P mode from the title.
    pad1Trig = pad_trigger(0);
    pad1     = pad_state(0);

    // Sense the Zapper on PORT 2. ppu_wait_nmi() returned at the START of vblank,
    // so this spin runs through the rest of vblank and on into the active picture;
    // over POLL_READS reads it spans a full visible frame, so the beam is
    // guaranteed to cross the muzzle's scanline during it. light = any read with D3
    // clear (a bright pixel sensed); trig2 = any read with D4 set.
    light = 0; trig2 = 0;
    for (pr = 0; pr < POLL_READS; ++pr) {
      z = CTRL_PORT2;
      if (!(z & 0x08)) light = 1;   // D3 == 0  → photodiode saw light (on target)
      if (z & 0x10)    trig2 = 1;   // D4 == 1  → trigger held
    }

    if (state == ST_PLAY) {
      // Resolve a shot. Each shot is attributed to a player; only one HIT/MISS
      // event per player per frame (edge-triggered), so a held trigger fires once.
      if (mode == MODE_DUEL) {
        // Simultaneous: P1 = port-1 A button, P2 = Zapper trigger. Both resolve
        // against the shared light sense this frame (each gun aims the photodiode
        // on its own read once the multiport core is live).
        u8 fired = 0;
        if (pad1Trig & PAD_A)       { if (light) do_hit(0); else do_miss(0); fired = 1; }
        if (state == ST_PLAY && trig2 && !trig2Prev) {
          if (light) do_hit(1); else do_miss(1); fired = 1;
        }
        if (!fired && t_timer) {
          // Timeout is charged to whoever is "on the clock" — alternate so a
          // shared-field timeout doesn't always punish the same player.
          if (--t_timer == 0) { do_miss(cur); cur ^= 1; }
        }
      } else {
        // SOLO and SHARE both fire with the single Zapper (port 2). In SHARE the
        // active player `cur` owns the shot and the wave; SOLO is always player 0.
        if (trig2 && !trig2Prev) {
          if (light) do_hit(cur); else do_miss(cur);
          if (mode == MODE_SHARE && state == ST_PLAY) {
            if (wave) { if (--wave == 0) { if (!pass_turn()) { enter_over(); state = ST_OVER; } } }
          }
        } else if (t_timer) {
          if (--t_timer == 0) {
            do_miss(cur);
            if (mode == MODE_SHARE && state == ST_PLAY) {
              if (wave) { if (--wave == 0) { if (!pass_turn()) { enter_over(); state = ST_OVER; } } }
            }
          }
        }
      }

      // Build the target sprites for the next frame, tinted to the active player's
      // palette family (P1 = spr palette 0, P2 = spr palette 1) so SHARE turns and
      // DUEL ownership read at a glance.
      target_meta[3]  = (cur ? 1 : 0);
      target_meta[7]  = (cur ? 1 : 0);
      target_meta[11] = (cur ? 1 : 0);
      target_meta[15] = (cur ? 1 : 0);
      oam_clear();
      sid = oam_meta_spr(tx, ty, 0, target_meta);
      oam_hide_rest(sid);
    } else {
      // Title / game-over: no sprites. From the TITLE, the input picks the mode:
      //   * Zapper trigger          → 1P SOLO
      //   * port-1 START             → 2P SHARE (alternating turns, one gun)
      //   * port-1 A (a 2nd gun fire)→ 2P DUEL  (simultaneous), auto-armed
      // From GAME OVER any trigger restarts with the same mode.
      oam_clear();
      oam_hide_rest(0);
      if (state == ST_TITLE) {
        if (pad1Trig & PAD_A)          { mode = MODE_DUEL;  start_game(); }
        else if (pad1Trig & PAD_START) { mode = MODE_SHARE; start_game(); }
        else if (trig2 && !trig2Prev)  { mode = MODE_SOLO;  start_game(); }
      } else { /* ST_OVER */
        // A port-1 A fire keeps DUEL alive; otherwise the Zapper restarts the
        // currently selected mode.
        if (pad1Trig & PAD_A)          { mode = MODE_DUEL;  start_game(); }
        else if (trig2 && !trig2Prev)  { start_game(); }
      }
    }

    trig2Prev = trig2;
  }
}
