// LWX Genesis Demo -- a tiny CC0 Sega Genesis / Mega Drive game for the
// LibretroWebXR project's playable test content.
//
// One screen: a 16x16 sprite you move around with the D-pad on a tiled,
// two-tone background. Press A/B/C to recolour the sprite. That's it -- the
// smallest "it works, it's controllable, it's ours" deliverable.
//
// HARDWARE/BOOT POLICY: every byte of boot code, the ROM header
// (src/boot/rom_head.c) and the m68k vector table are generated by SGDK's
// frozen, known-good template via `make -f makefile.gen`. Nothing here touches
// raw VDP registers, the sprite attribute table layout, DMA or vblank timing
// by hand -- it is all done through SGDK's documented API (VDP_*, JOY_*,
// PAL_*, SYS_doVBlankProcess). This file is the only "ours to write" part.
//
// All artwork is defined inline as tile data, so the build needs no PNG assets
// and no rescomp step -- it is fully deterministic from this one C file.
//
// License: CC0 1.0 (public domain dedication). Authored for LibretroWebXR.

#include <genesis.h>

// ---- tiles -----------------------------------------------------------------
// SGDK tile format: 8x8 pixels, 4 bits per pixel (palette index 0..15),
// stored as 8 u32 rows, two pixels per byte (high nibble = left pixel).

// Background tile A: solid palette index 1.
static const u32 tileBgA[8] = {
    0x11111111, 0x11111111, 0x11111111, 0x11111111,
    0x11111111, 0x11111111, 0x11111111, 0x11111111
};

// Background tile B: solid palette index 2 (gives a checkerboard with A).
static const u32 tileBgB[8] = {
    0x22222222, 0x22222222, 0x22222222, 0x22222222,
    0x22222222, 0x22222222, 0x22222222, 0x22222222
};

// Player sprite is 16x16 = 4 tiles (2x2). The hardware reads a 2x2 sprite as
// 4 consecutive tiles in COLUMN order (TL, BL, TR, BR). We draw a simple
// rounded diamond using palette index 5 (body) and 6 (outline) so the colour
// swap on button press is visible. Each constant below is one 8x8 tile.

// Top-left quarter.
static const u32 tilePlTL[8] = {
    0x00000066, 0x00000655, 0x00006555, 0x00065555,
    0x00655555, 0x06555555, 0x06555555, 0x65555555
};
// Bottom-left quarter.
static const u32 tilePlBL[8] = {
    0x65555555, 0x06555555, 0x06555555, 0x00655555,
    0x00065555, 0x00006555, 0x00000655, 0x00000066
};
// Top-right quarter.
static const u32 tilePlTR[8] = {
    0x66000000, 0x55560000, 0x55556000, 0x55555600,
    0x55555560, 0x55555560, 0x55555556, 0x55555556
};
// Bottom-right quarter.
static const u32 tilePlBR[8] = {
    0x55555556, 0x55555556, 0x55555560, 0x55555560,
    0x55555600, 0x55556000, 0x55560000, 0x66000000
};

// VRAM tile layout (user tiles start at TILE_USER_INDEX).
#define TILE_BG_A   (TILE_USER_INDEX + 0)
#define TILE_BG_B   (TILE_USER_INDEX + 1)
#define TILE_PLAYER (TILE_USER_INDEX + 2)  // 4 tiles: +2,+3,+4,+5

// Screen / movement parameters.
#define SPR_SIZE    16
#define SPEED       2
#define X_MIN       0
#define Y_MIN       0
#define X_MAX       (320 - SPR_SIZE)
#define Y_MAX       (224 - SPR_SIZE)

// Player palette variants (VDP colours). Index 5 = body, 6 = outline.
// PAL1 is the sprite palette here; we only ever rewrite slots 5 and 6.
static const u16 bodyColors[3] = {
    RGB24_TO_VDPCOLOR(0xFFCC22),   // A: gold
    RGB24_TO_VDPCOLOR(0x33DD55),   // B: green
    RGB24_TO_VDPCOLOR(0x4488FF)    // C: blue
};

static void setupBackground(void)
{
    // BG palette (PAL0): two muted tones for the checkerboard.
    PAL_setColor(0, RGB24_TO_VDPCOLOR(0x101830));   // colour 0 (also backdrop)
    PAL_setColor(1, RGB24_TO_VDPCOLOR(0x283860));   // tile A
    PAL_setColor(2, RGB24_TO_VDPCOLOR(0x1c2848));   // tile B
    VDP_setBackgroundColor(0);

    // Upload the two background tiles.
    VDP_loadTileData(tileBgA, TILE_BG_A, 1, DMA);
    VDP_loadTileData(tileBgB, TILE_BG_B, 1, DMA);

    // Paint a checkerboard across plane B (40x28 cells visible).
    {
        u16 cx, cy;
        for (cy = 0; cy < 28; cy++)
        {
            for (cx = 0; cx < 40; cx++)
            {
                u16 t = ((cx ^ cy) & 1) ? TILE_BG_A : TILE_BG_B;
                VDP_setTileMapXY(BG_B, TILE_ATTR_FULL(PAL0, FALSE, FALSE, FALSE, t), cx, cy);
            }
        }
    }
}

static void setupPlayer(void)
{
    // Sprite palette (PAL1): outline + body. Body starts as variant 0.
    PAL_setColor(16 + 6, RGB24_TO_VDPCOLOR(0x000000));   // PAL1 colour 6: outline
    PAL_setColor(16 + 5, bodyColors[0]);                 // PAL1 colour 5: body

    // Upload the four player tiles in column order (TL, BL, TR, BR).
    VDP_loadTileData(tilePlTL, TILE_PLAYER + 0, 1, DMA);
    VDP_loadTileData(tilePlBL, TILE_PLAYER + 1, 1, DMA);
    VDP_loadTileData(tilePlTR, TILE_PLAYER + 2, 1, DMA);
    VDP_loadTileData(tilePlBR, TILE_PLAYER + 3, 1, DMA);
}

int main(bool hardReset)
{
    s16 px = (X_MAX / 2);
    s16 py = (Y_MAX / 2);
    u8  colorIdx = 0;
    u16 prevJoy = 0;

    SYS_disableInts();

    VDP_setScreenWidth320();
    VDP_clearPlane(BG_A, TRUE);
    VDP_clearPlane(BG_B, TRUE);

    setupBackground();
    setupPlayer();

    // A short caption on plane A (uses the SGDK font, PAL0).
    VDP_setTextPalette(PAL0);
    PAL_setColor(15, RGB24_TO_VDPCOLOR(0xC8D0E8));   // readable font colour
    VDP_drawText("LWX GENESIS DEMO - D-PAD MOVE, A/B/C COLOR", 0, 0);

    SYS_enableInts();

    while (TRUE)
    {
        u16 joy = JOY_readJoypad(JOY_1);
        u16 pressed = joy & ~prevJoy;   // newly-pressed edges
        prevJoy = joy;

        // D-pad movement with edge clamping.
        if (joy & BUTTON_LEFT)  px -= SPEED;
        if (joy & BUTTON_RIGHT) px += SPEED;
        if (joy & BUTTON_UP)    py -= SPEED;
        if (joy & BUTTON_DOWN)  py += SPEED;

        if (px < X_MIN) px = X_MIN;
        if (px > X_MAX) px = X_MAX;
        if (py < Y_MIN) py = Y_MIN;
        if (py > Y_MAX) py = Y_MAX;

        // Recolour the body on a fresh A/B/C press.
        if (pressed & BUTTON_A) colorIdx = 0;
        if (pressed & BUTTON_B) colorIdx = 1;
        if (pressed & BUTTON_C) colorIdx = 2;
        if (pressed & (BUTTON_A | BUTTON_B | BUTTON_C))
            PAL_setColor(16 + 5, bodyColors[colorIdx]);

        // Place the player as a single 16x16 hardware sprite (cache + DMA up).
        VDP_setSpriteFull(0, px, py, SPRITE_SIZE(2, 2),
                          TILE_ATTR_FULL(PAL1, TRUE, FALSE, FALSE, TILE_PLAYER), 0);
        VDP_updateSprites(1, DMA);

        SYS_doVBlankProcess();   // sync to vblank; required each frame
    }

    return 0;
}
