.include "hdr.asm"

.section ".rodata1" superfree

; Console font, used as the background tile set + on-screen text.
tilfont:
.incbin "pvsneslibfont.pic"
palfont:
.incbin "pvsneslibfont.pal"

.ends

; Player sprite graphics + palette (generated by gfx4snes from sprites.bmp).
.section ".rosprite" superfree

.include "sprites_data.as"

.ends
