// LWX Bomberman — a CC0 NES game for LibretroWebXR test content.
//
// A grid-based Bomberman / Dynablaster clone. NROM (mapper 0), single screen.
// The whole arena — floor, indestructible walls, destructible bricks, ticking
// bombs and explosion flames — lives in the background nametable and is
// repainted incrementally through neslib's set_vram_update buffer; only the
// players are sprites. Up to FOUR players via the NES Four Score: P1/P2 are the
// two hardware ports, P3/P4 the multitap's extra pads. The Four Score is
// auto-detected from its signature, so with a plain 2-controller setup (or an
// emulator without Four Score) the game cleanly runs as 2-player.
//
// Controls: D-pad moves, A drops a bomb. Bombs explode after ~2s, throwing
// flame outward (range grows with fire power-ups), stopping at walls and
// consuming the first brick hit. Bricks may hide power-ups: bomb-up (one more
// simultaneous bomb), fire-up (longer blast), speed-up (move faster). Last
// player standing wins, then the round rebuilds. CC0.

#include "neslib.h"

typedef unsigned char u8;
typedef signed char   s8;
typedef unsigned int  u16;

// Required by the vendored display.sinc (it references a C-side zeropage byte).
#pragma bss-name (push,"ZEROPAGE")
#pragma data-name (push,"ZEROPAGE")
u8 oam_off;
#pragma data-name(pop)
#pragma bss-name (pop)

// ---- arena geometry --------------------------------------------------------
#define GW     11           // grid width in cells  (cols 0..10, border incl.)
#define GH     9            // grid height in cells (rows 0..8,  border incl.)
#define STRIDE 16           // row stride (power of two -> index without mul)
#define ORX    40           // pixel x of cell (0,0): ((32-22)/2)*8
#define ORY    48           // pixel y of cell (0,0): ((30-18)/2)*8
#define OTX    5            // tile-column origin (ORX/8)
#define OTY    6            // tile-row origin    (ORY/8)
#define IDX(x,y) (((y) << 4) + (x))

// ---- cell types (grid[] low nibble; high nibble = hidden item under a brick)
#define C_FLOOR 0
#define C_WALL  1
#define C_BRICK 2
#define C_BOMB  3

// ---- power-up item ids (grid high nibble + item[] floor array) -------------
#define ITEM_BOMBS 1        // +1 simultaneous bomb
#define ITEM_FIRE  2        // +1 blast range
#define ITEM_SPEED 3        // +1 move speed

// ---- CHR tile ids (generated by make-nes-bomberman.mjs) --------------------
#define T_FLOOR 0
#define T_WALL  1
#define T_BRICK 2
#define T_BOMB0 3           // bomb is 4 tiles: TL,TR,BL,BR = 3,4,5,6
#define T_FLAME 7
#define T_PLR0  8           // player is 4 tiles: TL,TR,BL,BR = 8,9,10,11
#define T_ITEM_BOMBS 12
#define T_ITEM_FIRE  13
#define T_ITEM_SPEED 14

// ---- tunables --------------------------------------------------------------
#define BASE_SPEED 2        // starting player px/frame (16/2 = 8 frames/cell)
#define MAX_SPEED  4        // speed power-up cap
#define MAX_RANGE  8        // fire power-up cap
#define MAX_PBOMB  6        // bomb power-up cap
#define BOMB_FUSE  120      // frames a bomb ticks before exploding (~2s)
#define FLAME_DUR  15       // frames a flame cell burns
#define MAXBOMBS   16       // global live-bomb slots (shared by all players)
#define ITEM_CHANCE 64      // rand8() < N -> brick hides an item (~25%)
#define OVER_WAIT  150      // frames to show the result before restarting

// ---- state -----------------------------------------------------------------
static u8 grid[GH * STRIDE];   // low nibble = type, high nibble = hidden item
static u8 flame[GH * STRIDE];  // flame countdown per cell (0 = none)
static u8 dirty[GH * STRIDE];  // queued-for-repaint flag (avoids dup enqueues)
static u8 item[GH * STRIDE];   // power-up lying on the floor (0 = none)

static u8 dq[64], dqHead, dqTail, dqCount;     // redraw queue (cell indices)

static u8 bcx[MAXBOMBS], bcy[MAXBOMBS], bt[MAXBOMBS], bown[MAXBOMBS];

static u8 pcx[4], pcy[4];      // current logical cell
static u8 pmoving[4], pmdir[4], pmoff[4];
static u8 palive[4], pprev[4], pbombs[4];
static u8 pMaxBombs[4], pRange[4], pSpeed[4];

static u8 pads[4];             // per-player button state (filled by poll4)
static u8 fourscore;           // 1 once a Four Score signature is seen
static u8 nplayers;            // 2 or 4, fixed at the start of each round

static u8 vbuf[140];           // set_vram_update buffer

// global scratch (keeps the cc65 software stack shallow)
static u8 i, j, p, k, n, spr, t0, t1, t2, t3, cx, cy, idx, dir;
static u8 alive, winner, over, gameframe, px, py, sx, sy, rng;
static u16 addr;

// spawn cells, indexed by player (corners)
static const u8 SPX[4] = { 1, GW - 2, GW - 2, 1 };
static const u8 SPY[4] = { 1, GH - 2, 1, GH - 2 };

// step deltas per direction (0=up,1=down,2=left,3=right)
static const s8 DCX[4] = {  0, 0, -1, 1 };
static const s8 DCY[4] = { -1, 1,  0, 0 };

// palettes: 16 bg + 16 sprite
static const u8 PALETTE[32] = {
  // bg: 0 floor(black) 1 wall(gray) 2 red 3 yellow  (bricks, flame, items)
  0x0f, 0x00, 0x16, 0x28,  0x0f, 0x00, 0x16, 0x28,
  0x0f, 0x00, 0x16, 0x28,  0x0f, 0x00, 0x16, 0x28,
  // spr: P1 white/red, P2 light-blue, P3 green, P4 yellow
  0x0f, 0x30, 0x16, 0x0f,  0x0f, 0x21, 0x11, 0x0f,
  0x0f, 0x2a, 0x19, 0x0f,  0x0f, 0x28, 0x17, 0x0f,
};

// Read all four pads in one strobe via the Four Score serial protocol, and
// detect the multitap from its signature. $4016 is written to strobe (never
// $4017, which doubles as the APU frame counter). Bits pack LSB-first to match
// neslib's PAD_* masks (bit0 = A ... bit7 = Right).
static void poll4(void) {
  u8 c, s0, s1;
  *(volatile u8 *)0x4016 = 1;
  *(volatile u8 *)0x4016 = 0;
  pads[0] = pads[1] = pads[2] = pads[3] = s0 = s1 = 0;
  for (c = 0; c < 8; ++c) {       // bits 1-8: P1 (port0), P2 (port1)
    pads[0] = (pads[0] >> 1) | ((*(volatile u8 *)0x4016 & 1) << 7);
    pads[1] = (pads[1] >> 1) | ((*(volatile u8 *)0x4017 & 1) << 7);
  }
  for (c = 0; c < 8; ++c) {       // bits 9-16: P3 (port0), P4 (port1)
    pads[2] = (pads[2] >> 1) | ((*(volatile u8 *)0x4016 & 1) << 7);
    pads[3] = (pads[3] >> 1) | ((*(volatile u8 *)0x4017 & 1) << 7);
  }
  for (c = 0; c < 8; ++c) {       // bits 17-24: Four Score signature
    s0 = (s0 >> 1) | ((*(volatile u8 *)0x4016 & 1) << 7);
    s1 = (s1 >> 1) | ((*(volatile u8 *)0x4017 & 1) << 7);
  }
  // Signature is 0b00010000 / 0b00100000; accept either bit order. A plain
  // controller returns $ff here, so it never false-positives.
  if ((s0 == 0x10 || s0 == 0x08) && (s1 == 0x20 || s1 == 0x04)) fourscore = 1;
}

// Compute the four nametable tiles for cell (cx,cy) into t0..t3; sets idx,n.
static void cell_tiles(void) {
  idx = IDX(cx, cy);
  if (flame[idx]) { t0 = t1 = t2 = t3 = T_FLAME; return; }
  n = grid[idx] & 0x0f;
  if (n == C_FLOOR) {
    k = item[idx];
    if      (k == ITEM_BOMBS) { t0 = t1 = t2 = t3 = T_ITEM_BOMBS; }
    else if (k == ITEM_FIRE)  { t0 = t1 = t2 = t3 = T_ITEM_FIRE;  }
    else if (k == ITEM_SPEED) { t0 = t1 = t2 = t3 = T_ITEM_SPEED; }
    else                      { t0 = t1 = t2 = t3 = T_FLOOR;      }
  }
  else if (n == C_WALL)  { t0 = t1 = t2 = t3 = T_WALL;  }
  else if (n == C_BRICK) { t0 = t1 = t2 = t3 = T_BRICK; }
  else { t0 = T_BOMB0; t1 = T_BOMB0 + 1; t2 = T_BOMB0 + 2; t3 = T_BOMB0 + 3; }
}

// Queue cell (cx,cy) for an incremental nametable repaint (dedups via dirty[]).
static void mark(void) {
  idx = IDX(cx, cy);
  if (dirty[idx] || dqCount >= 64) return;
  dirty[idx] = 1;
  dq[dqTail] = idx;
  dqTail = (dqTail + 1) & 63;
  ++dqCount;
}

// Paint cell (cx,cy) straight to VRAM — only valid while rendering is off.
static void paint_direct(void) {
  cell_tiles();
  addr = (u16)0x2000 | ((u16)(OTY + (cy << 1)) << 5) | (OTX + (cx << 1));
  vram_adr(addr);      vram_put(t0); vram_put(t1);
  vram_adr(addr + 32); vram_put(t2); vram_put(t3);
}

// Drain up to 10 queued cells into the vram_update buffer (applied next NMI).
static void build_vbuf(void) {
  p = 0;
  n = 0;
  while (dqCount && n < 10) {
    idx = dq[dqHead];
    dqHead = (dqHead + 1) & 63;
    --dqCount;
    dirty[idx] = 0;
    cx = idx & 15;
    cy = idx >> 4;
    cell_tiles();
    addr = (u16)0x2000 | ((u16)(OTY + (cy << 1)) << 5) | (OTX + (cx << 1));
    vbuf[p++] = (u8)(addr >> 8) | NT_UPD_HORZ;
    vbuf[p++] = (u8)addr;
    vbuf[p++] = 2;
    vbuf[p++] = t0;
    vbuf[p++] = t1;
    addr += 32;
    vbuf[p++] = (u8)(addr >> 8) | NT_UPD_HORZ;
    vbuf[p++] = (u8)addr;
    vbuf[p++] = 2;
    vbuf[p++] = t2;
    vbuf[p++] = t3;
    ++n;
  }
  vbuf[p] = NT_UPD_EOF;
  set_vram_update(vbuf);
}

// Is cell (cx,cy) free to walk into? (unsigned wrap also rejects <0)
static u8 walkable(void) {
  if (cx >= GW || cy >= GH) return 0;
  return (grid[IDX(cx, cy)] & 0x0f) == C_FLOOR;
}

// Light cell (cx,cy) on fire and queue its repaint.
static void set_flame(void) {
  flame[IDX(cx, cy)] = FLAME_DUR;
  mark();
}

// A blast reached a bomb at (cx,cy): make it detonate on the next tick (chain).
static void trigger_bomb_at(void) {
  for (k = 0; k < MAXBOMBS; ++k)
    if (bt[k] && bcx[k] == cx && bcy[k] == cy) { bt[k] = 1; break; }
}

// Detonate bomb slot p: clear it, then spread flame pRange cells each way,
// stopping at walls and consuming the first brick (revealing its hidden item)
// or chaining a bomb it hits.
static void explode(void) {
  if (pbombs[bown[p]]) --pbombs[bown[p]];
  rng = pRange[bown[p]];
  cx = bcx[p];
  cy = bcy[p];
  grid[IDX(cx, cy)] = C_FLOOR;
  bt[p] = 0;
  set_flame();                       // centre
  for (dir = 0; dir < 4; ++dir) {
    cx = bcx[p];
    cy = bcy[p];
    for (j = 1; j <= rng; ++j) {
      cx += DCX[dir];
      cy += DCY[dir];
      if (cx >= GW || cy >= GH) break;
      idx = IDX(cx, cy);
      n = grid[idx] & 0x0f;
      if (n == C_WALL) break;
      if (n == C_BRICK) {
        k = grid[idx] >> 4;          // hidden item, if any
        grid[idx] = C_FLOOR;
        if (k) item[idx] = k;        // reveal it on the floor
        set_flame();
        break;
      }
      if (n == C_BOMB) { trigger_bomb_at(); set_flame(); break; }
      set_flame();
    }
  }
}

// Player p drops a bomb on their current cell, up to their bomb allowance.
static void try_bomb(void) {
  if (pbombs[p] >= pMaxBombs[p]) return;
  cx = pcx[p];
  cy = pcy[p];
  idx = IDX(cx, cy);
  if ((grid[idx] & 0x0f) != C_FLOOR) return;
  for (k = 0; k < MAXBOMBS; ++k) {
    if (!bt[k]) {
      bcx[k] = cx; bcy[k] = cy; bt[k] = BOMB_FUSE; bown[k] = p;
      grid[idx] = C_BOMB; ++pbombs[p];
      mark();
      return;
    }
  }
}

// Clear cell (cx,cy) back to floor if it is a brick (drops any hidden item too).
static void clear_one(void) {
  if (cx < GW && cy < GH) {
    idx = IDX(cx, cy);
    if ((grid[idx] & 0x0f) == C_BRICK) grid[idx] = C_FLOOR;
  }
}

// Keep a spawn (sx,sy) clear, with 2-cell arms so a player can always retreat
// out of their own (range-1) first blast instead of being boxed into the corner.
static void clear_safe(void) {
  cx = sx;     cy = sy;     clear_one();
  cx = sx + 1; cy = sy;     clear_one();
  cx = sx + 2; cy = sy;     clear_one();
  cx = sx - 1; cy = sy;     clear_one();
  cx = sx - 2; cy = sy;     clear_one();
  cx = sx;     cy = sy + 1; clear_one();
  cx = sx;     cy = sy + 2; clear_one();
  cx = sx;     cy = sy - 1; clear_one();
  cx = sx;     cy = sy - 2; clear_one();
}

// Build a fresh arena and reset all entities, then enable rendering.
static void new_round(void) {
  ppu_off();
  pal_all(PALETTE);
  vram_adr(NAMETABLE_A);
  vram_fill(T_FLOOR, 32 * 30);
  vram_adr(0x23c0);
  vram_fill(0, 64);                   // attributes -> bg palette 0 everywhere

  for (i = 0; i < GH * STRIDE; ++i) { grid[i] = C_FLOOR; flame[i] = 0; dirty[i] = 0; item[i] = 0; }
  for (i = 0; i < MAXBOMBS; ++i) bt[i] = 0;
  dqHead = dqTail = dqCount = 0;
  nplayers = fourscore ? 4 : 2;

  // border walls + interior pillars (even col & even row)
  for (cy = 0; cy < GH; ++cy)
    for (cx = 0; cx < GW; ++cx) {
      idx = IDX(cx, cy);
      if (cx == 0 || cy == 0 || cx == GW - 1 || cy == GH - 1) grid[idx] = C_WALL;
      else if (!(cx & 1) && !(cy & 1))                        grid[idx] = C_WALL;
    }
  // scatter destructible bricks on the open floor, some hiding a power-up
  for (cy = 1; cy < GH - 1; ++cy)
    for (cx = 1; cx < GW - 1; ++cx) {
      idx = IDX(cx, cy);
      if ((grid[idx] & 0x0f) == C_FLOOR && rand8() < 150) {
        grid[idx] = C_BRICK;
        n = rand8();
        if (n < ITEM_CHANCE) {
          k = (n < 17) ? ITEM_BOMBS : (n < 34) ? ITEM_FIRE : ITEM_SPEED;
          grid[idx] = C_BRICK | (k << 4);
        }
      }
    }
  // keep the four corners playable
  for (i = 0; i < 4; ++i) { sx = SPX[i]; sy = SPY[i]; clear_safe(); }

  for (cy = 0; cy < GH; ++cy)
    for (cx = 0; cx < GW; ++cx) paint_direct();

  for (p = 0; p < 4; ++p) {
    pcx[p] = SPX[p]; pcy[p] = SPY[p];
    pmoving[p] = 0; pmoff[p] = 0; pprev[p] = 0; pbombs[p] = 0;
    pMaxBombs[p] = 1; pRange[p] = 1; pSpeed[p] = BASE_SPEED;
    palive[p] = (p < nplayers);
  }
  over = 0;
  winner = 255;
  ppu_on_all();
}

void main(void) {
  // Drop straight into a live, playable arena. The old title screen was a BLACK
  // nametable (floor tile 0 painted with the black floor palette) that simply
  // waited for START — on screen it was indistinguishable from a hung or blank
  // console, and START may not even route to a cartridge loaded into a SECONDARY
  // rack console. Booting the arena immediately means inserting the cart always
  // paints visible, playable content with no input required.
  //
  // A Four Score is still auto-detected by poll4() in the main loop below, so the
  // game upgrades 2->4 players on the next round once the signature is seen.
  // The first arena uses a fixed seed (deterministic layout); rand8() state then
  // advances through play, so each subsequent round is freshly randomised.
  set_rand(0x4711);
  new_round();

  while (1) {
    ppu_wait_nmi();
    poll4();

    if (over) {
      if (--gameframe == 0) new_round();
    } else {
      // --- players: input, movement, bomb drops ---
      for (p = 0; p < 4; ++p) {
        if (!palive[p]) continue;
        if (!pmoving[p]) {
          dir = 255;
          if      (pads[p] & PAD_UP)    dir = 0;
          else if (pads[p] & PAD_DOWN)  dir = 1;
          else if (pads[p] & PAD_LEFT)  dir = 2;
          else if (pads[p] & PAD_RIGHT) dir = 3;
          if (dir != 255) {
            cx = pcx[p] + DCX[dir];
            cy = pcy[p] + DCY[dir];
            if (walkable()) { pmoving[p] = 1; pmdir[p] = dir; pmoff[p] = 0; }
          }
        }
        if (pmoving[p]) {
          pmoff[p] += pSpeed[p];
          if (pmoff[p] >= 16) {
            pcx[p] += DCX[pmdir[p]];
            pcy[p] += DCY[pmdir[p]];
            pmoving[p] = 0; pmoff[p] = 0;
            // collect a power-up on arrival
            idx = IDX(pcx[p], pcy[p]);
            if (item[idx]) {
              k = item[idx];
              if      (k == ITEM_BOMBS) { if (pMaxBombs[p] < MAX_PBOMB) ++pMaxBombs[p]; }
              else if (k == ITEM_FIRE)  { if (pRange[p]    < MAX_RANGE) ++pRange[p];    }
              else                      { if (pSpeed[p]    < MAX_SPEED) ++pSpeed[p];    }
              item[idx] = 0;
              cx = pcx[p]; cy = pcy[p]; mark();
            }
          }
        }
        if ((pads[p] & PAD_A) && !(pprev[p] & PAD_A)) try_bomb();
        pprev[p] = pads[p];
      }

      // --- bombs: tick & detonate (chains cascade within the frame) ---
      for (i = 0; i < MAXBOMBS; ++i)
        if (bt[i] && --bt[i] == 0) { p = i; explode(); }

      // --- flames: burn down, repaint on expiry ---
      for (cy = 0; cy < GH; ++cy)
        for (cx = 0; cx < GW; ++cx) {
          idx = IDX(cx, cy);
          if (flame[idx] && --flame[idx] == 0) mark();
        }

      // --- deaths & win check ---
      alive = 0;
      for (p = 0; p < 4; ++p) {
        if (!palive[p]) continue;
        cx = pcx[p]; cy = pcy[p];
        if (flame[IDX(cx, cy)]) { palive[p] = 0; continue; }
        if (pmoving[p]) {
          cx = pcx[p] + DCX[pmdir[p]];
          cy = pcy[p] + DCY[pmdir[p]];
          if (flame[IDX(cx, cy)]) { palive[p] = 0; continue; }
        }
        ++alive;
        winner = p;
      }
      if (alive <= 1) { over = 1; gameframe = OVER_WAIT; if (alive == 0) winner = 255; }
    }

    // --- render players (sprites, drawn over the nametable arena) ---
    spr = 0;
    for (p = 0; p < 4; ++p) {
      if (!palive[p]) continue;
      px = ORX + (pcx[p] << 4);
      py = ORY + (pcy[p] << 4);
      if (pmoving[p]) {
        px += DCX[pmdir[p]] * pmoff[p];
        py += DCY[pmdir[p]] * pmoff[p];
      }
      spr = oam_spr(px,     py,     T_PLR0,     p, spr);
      spr = oam_spr(px + 8, py,     T_PLR0 + 1, p, spr);
      spr = oam_spr(px,     py + 8, T_PLR0 + 2, p, spr);
      spr = oam_spr(px + 8, py + 8, T_PLR0 + 3, p, spr);
    }
    oam_hide_rest(spr);

    build_vbuf();
  }
}
