// LWX Bomberman — a CC0 NES game for LibretroWebXR test content.
//
// A grid-based two-player Bomberman / Dynablaster clone. NROM (mapper 0),
// single screen. The whole arena — floor, indestructible walls, destructible
// bricks, ticking bombs and explosion flames — lives in the background
// nametable and is repainted incrementally through neslib's set_vram_update
// buffer; only the two players are sprites. Player 1 = D-pad + A on controller
// 0, Player 2 = the same on controller 1 (which the WebXR frontend forwards as
// host controller 1 in a shared room, so it doubles as a multiplayer test).
//
// Phase 1: 2 players, fixed bomb range, last-one-standing wins. Four-player
// (Four Score) and power-ups are layered on later. All hardware/timing lives
// in the frozen neslib boilerplate (crt0.s, *.sinc); this file is just game
// logic calling neslib's documented API. CC0.

#include "neslib.h"

typedef unsigned char u8;
typedef signed char   s8;
typedef unsigned int  u16;

// Required by the vendored display.sinc (it references a C-side zeropage byte).
#pragma bss-name (push,"ZEROPAGE")
#pragma data-name (push,"ZEROPAGE")
u8 oam_off;
#pragma data-name(pop)
#pragma bss-name (pop)

// ---- arena geometry --------------------------------------------------------
#define GW     11           // grid width in cells  (cols 0..10, border incl.)
#define GH     9            // grid height in cells (rows 0..8,  border incl.)
#define STRIDE 16           // row stride (power of two -> index without mul)
#define ORX    40           // pixel x of cell (0,0): ((32-22)/2)*8
#define ORY    48           // pixel y of cell (0,0): ((30-18)/2)*8
#define OTX    5            // tile-column origin (ORX/8)
#define OTY    6            // tile-row origin    (ORY/8)
#define IDX(x,y) (((y) << 4) + (x))

// ---- cell types (grid[]) ---------------------------------------------------
#define C_FLOOR 0
#define C_WALL  1
#define C_BRICK 2
#define C_BOMB  3

// ---- CHR tile ids (generated by make-nes-bomberman.mjs) --------------------
#define T_FLOOR 0
#define T_WALL  1
#define T_BRICK 2
#define T_BOMB0 3           // bomb is 4 tiles: TL,TR,BL,BR = 3,4,5,6
#define T_FLAME 7
#define T_PLR0  8           // player is 4 tiles: TL,TR,BL,BR = 8,9,10,11

// ---- tunables --------------------------------------------------------------
#define SPEED     2         // player px/frame (16/2 = 8 frames per cell)
#define BOMB_FUSE 120       // frames a bomb ticks before exploding (~2s)
#define FLAME_DUR 15        // frames a flame cell burns
#define RANGE     2         // bomb blast reach in cells
#define MAXBOMBS  8         // global live-bomb slots
#define NUMP      2         // active players this phase
#define OVER_WAIT 150       // frames to show the result before restarting

// ---- state -----------------------------------------------------------------
static u8 grid[GH * STRIDE];   // cell type
static u8 flame[GH * STRIDE];  // flame countdown per cell (0 = none)
static u8 dirty[GH * STRIDE];  // queued-for-repaint flag (avoids dup enqueues)

static u8 dq[64], dqHead, dqTail, dqCount;     // redraw queue (cell indices)

static u8 bcx[MAXBOMBS], bcy[MAXBOMBS], bt[MAXBOMBS], bown[MAXBOMBS];

static u8 pcx[4], pcy[4];      // current logical cell
static u8 pmoving[4], pmdir[4], pmoff[4];
static u8 palive[4], pprev[4], pbombs[4];

static u8 vbuf[140];           // set_vram_update buffer

// global scratch (keeps the cc65 software stack shallow)
static u8 i, j, p, k, n, spr, t0, t1, t2, t3, cx, cy, idx, dir, pad;
static u8 alive, winner, over, gameframe, px, py, sx, sy;
static u16 addr, seed;

// step deltas per direction (0=up,1=down,2=left,3=right)
static const s8 DCX[4] = {  0, 0, -1, 1 };
static const s8 DCY[4] = { -1, 1,  0, 0 };

// palettes: 16 bg + 16 sprite
static const u8 PALETTE[32] = {
  // bg: 0 floor(black) 1 wall(gray) 2 brick(red) 3 mortar/flame-core(yellow)
  0x0f, 0x00, 0x16, 0x28,  0x0f, 0x00, 0x16, 0x28,
  0x0f, 0x00, 0x16, 0x28,  0x0f, 0x00, 0x16, 0x28,
  // spr: P1 white/red, P2 light-blue, (P3 green, P4 yellow reserved)
  0x0f, 0x30, 0x16, 0x0f,  0x0f, 0x21, 0x11, 0x0f,
  0x0f, 0x2a, 0x19, 0x0f,  0x0f, 0x28, 0x17, 0x0f,
};

// Compute the four nametable tiles for cell (cx,cy) into t0..t3; sets idx,n.
static void cell_tiles(void) {
  idx = IDX(cx, cy);
  if (flame[idx]) { t0 = t1 = t2 = t3 = T_FLAME; return; }
  n = grid[idx];
  if      (n == C_FLOOR) { t0 = t1 = t2 = t3 = T_FLOOR; }
  else if (n == C_WALL)  { t0 = t1 = t2 = t3 = T_WALL;  }
  else if (n == C_BRICK) { t0 = t1 = t2 = t3 = T_BRICK; }
  else { t0 = T_BOMB0; t1 = T_BOMB0 + 1; t2 = T_BOMB0 + 2; t3 = T_BOMB0 + 3; }
}

// Queue cell (cx,cy) for an incremental nametable repaint (dedups via dirty[]).
static void mark(void) {
  idx = IDX(cx, cy);
  if (dirty[idx] || dqCount >= 64) return;
  dirty[idx] = 1;
  dq[dqTail] = idx;
  dqTail = (dqTail + 1) & 63;
  ++dqCount;
}

// Paint cell (cx,cy) straight to VRAM — only valid while rendering is off.
static void paint_direct(void) {
  cell_tiles();
  addr = (u16)0x2000 | ((u16)(OTY + (cy << 1)) << 5) | (OTX + (cx << 1));
  vram_adr(addr);      vram_put(t0); vram_put(t1);
  vram_adr(addr + 32); vram_put(t2); vram_put(t3);
}

// Drain up to 10 queued cells into the vram_update buffer (applied next NMI).
static void build_vbuf(void) {
  p = 0;
  n = 0;
  while (dqCount && n < 10) {
    idx = dq[dqHead];
    dqHead = (dqHead + 1) & 63;
    --dqCount;
    dirty[idx] = 0;
    cx = idx & 15;
    cy = idx >> 4;
    cell_tiles();
    addr = (u16)0x2000 | ((u16)(OTY + (cy << 1)) << 5) | (OTX + (cx << 1));
    vbuf[p++] = (u8)(addr >> 8) | NT_UPD_HORZ;
    vbuf[p++] = (u8)addr;
    vbuf[p++] = 2;
    vbuf[p++] = t0;
    vbuf[p++] = t1;
    addr += 32;
    vbuf[p++] = (u8)(addr >> 8) | NT_UPD_HORZ;
    vbuf[p++] = (u8)addr;
    vbuf[p++] = 2;
    vbuf[p++] = t2;
    vbuf[p++] = t3;
    ++n;
  }
  vbuf[p] = NT_UPD_EOF;
  set_vram_update(vbuf);
}

// Is cell (cx,cy) free to walk into? (unsigned wrap also rejects <0)
static u8 walkable(void) {
  if (cx >= GW || cy >= GH) return 0;
  return grid[IDX(cx, cy)] == C_FLOOR;
}

// Light cell (cx,cy) on fire and queue its repaint.
static void set_flame(void) {
  flame[IDX(cx, cy)] = FLAME_DUR;
  mark();
}

// A blast reached a bomb at (cx,cy): make it detonate on the next tick (chain).
static void trigger_bomb_at(void) {
  for (k = 0; k < MAXBOMBS; ++k)
    if (bt[k] && bcx[k] == cx && bcy[k] == cy) { bt[k] = 1; break; }
}

// Detonate bomb slot p: clear it, then spread flames RANGE cells each way,
// stopping at walls and consuming the first brick (or chaining a bomb) hit.
static void explode(void) {
  if (pbombs[bown[p]]) --pbombs[bown[p]];
  cx = bcx[p];
  cy = bcy[p];
  grid[IDX(cx, cy)] = C_FLOOR;
  bt[p] = 0;
  set_flame();                       // centre
  for (dir = 0; dir < 4; ++dir) {
    cx = bcx[p];
    cy = bcy[p];
    for (j = 1; j <= RANGE; ++j) {
      cx += DCX[dir];
      cy += DCY[dir];
      if (cx >= GW || cy >= GH) break;
      n = grid[IDX(cx, cy)];
      if (n == C_WALL) break;
      if (n == C_BRICK) { grid[IDX(cx, cy)] = C_FLOOR; set_flame(); break; }
      if (n == C_BOMB)  { trigger_bomb_at(); set_flame(); break; }
      set_flame();
    }
  }
}

// Player p drops a bomb on their current cell (max 1 live bomb in phase 1).
static void try_bomb(void) {
  if (pbombs[p] >= 1) return;
  cx = pcx[p];
  cy = pcy[p];
  idx = IDX(cx, cy);
  if (grid[idx] != C_FLOOR) return;
  for (k = 0; k < MAXBOMBS; ++k) {
    if (!bt[k]) {
      bcx[k] = cx; bcy[k] = cy; bt[k] = BOMB_FUSE; bown[k] = p;
      grid[idx] = C_BOMB; ++pbombs[p];
      mark();
      return;
    }
  }
}

// Clear cell (cx,cy) back to floor if it is a brick (keeps walls intact).
static void clear_one(void) {
  if (cx < GW && cy < GH) {
    idx = IDX(cx, cy);
    if (grid[idx] == C_BRICK) grid[idx] = C_FLOOR;
  }
}

// Keep a spawn (sx,sy) and its orthogonal neighbours free of bricks.
static void clear_safe(void) {
  cx = sx;     cy = sy;     clear_one();
  cx = sx + 1; cy = sy;     clear_one();
  cx = sx - 1; cy = sy;     clear_one();
  cx = sx;     cy = sy + 1; clear_one();
  cx = sx;     cy = sy - 1; clear_one();
}

// Build a fresh arena and reset all entities, then enable rendering.
static void new_round(void) {
  ppu_off();
  pal_all(PALETTE);
  vram_adr(NAMETABLE_A);
  vram_fill(T_FLOOR, 32 * 30);
  vram_adr(0x23c0);
  vram_fill(0, 64);                   // attributes -> bg palette 0 everywhere

  for (i = 0; i < GH * STRIDE; ++i) { grid[i] = C_FLOOR; flame[i] = 0; dirty[i] = 0; }
  for (i = 0; i < MAXBOMBS; ++i) bt[i] = 0;
  dqHead = dqTail = dqCount = 0;

  // border walls + interior pillars (even col & even row)
  for (cy = 0; cy < GH; ++cy)
    for (cx = 0; cx < GW; ++cx) {
      idx = IDX(cx, cy);
      if (cx == 0 || cy == 0 || cx == GW - 1 || cy == GH - 1) grid[idx] = C_WALL;
      else if (!(cx & 1) && !(cy & 1))                        grid[idx] = C_WALL;
    }
  // scatter destructible bricks on the open floor
  for (cy = 1; cy < GH - 1; ++cy)
    for (cx = 1; cx < GW - 1; ++cx) {
      idx = IDX(cx, cy);
      if (grid[idx] == C_FLOOR && rand8() < 150) grid[idx] = C_BRICK;
    }
  // keep the four corners playable
  sx = 1;      sy = 1;      clear_safe();
  sx = GW - 2; sy = GH - 2; clear_safe();
  sx = GW - 2; sy = 1;      clear_safe();
  sx = 1;      sy = GH - 2; clear_safe();

  for (cy = 0; cy < GH; ++cy)
    for (cx = 0; cx < GW; ++cx) paint_direct();

  pcx[0] = 1;      pcy[0] = 1;
  pcx[1] = GW - 2; pcy[1] = GH - 2;
  pcx[2] = GW - 2; pcy[2] = 1;
  pcx[3] = 1;      pcy[3] = GH - 2;
  for (p = 0; p < 4; ++p) {
    pmoving[p] = 0; pmoff[p] = 0; pprev[p] = 0; pbombs[p] = 0;
    palive[p] = (p < NUMP);
  }
  over = 0;
  winner = 255;
  ppu_on_all();
}

void main(void) {
  // Title: blank field; advance a seed each frame until P1 presses START.
  ppu_off();
  pal_all(PALETTE);
  vram_adr(NAMETABLE_A);
  vram_fill(T_FLOOR, 32 * 30);
  vram_adr(0x23c0);
  vram_fill(0, 64);
  ppu_on_all();
  seed = 1;
  while (1) {
    ppu_wait_nmi();
    ++seed;
    if (pad_poll(0) & PAD_START) break;
  }
  set_rand(seed);
  new_round();

  while (1) {
    ppu_wait_nmi();

    if (over) {
      if (--gameframe == 0) new_round();
    } else {
      // --- players: input, movement, bomb drops ---
      for (p = 0; p < NUMP; ++p) {
        if (!palive[p]) { pprev[p] = 0; continue; }
        pad = pad_poll(p);
        if (!pmoving[p]) {
          dir = 255;
          if      (pad & PAD_UP)    dir = 0;
          else if (pad & PAD_DOWN)  dir = 1;
          else if (pad & PAD_LEFT)  dir = 2;
          else if (pad & PAD_RIGHT) dir = 3;
          if (dir != 255) {
            cx = pcx[p] + DCX[dir];
            cy = pcy[p] + DCY[dir];
            if (walkable()) { pmoving[p] = 1; pmdir[p] = dir; pmoff[p] = 0; }
          }
        }
        if (pmoving[p]) {
          pmoff[p] += SPEED;
          if (pmoff[p] >= 16) {
            pcx[p] += DCX[pmdir[p]];
            pcy[p] += DCY[pmdir[p]];
            pmoving[p] = 0; pmoff[p] = 0;
          }
        }
        if ((pad & PAD_A) && !(pprev[p] & PAD_A)) try_bomb();
        pprev[p] = pad;
      }

      // --- bombs: tick & detonate (chains cascade within the frame) ---
      for (i = 0; i < MAXBOMBS; ++i)
        if (bt[i] && --bt[i] == 0) { p = i; explode(); }

      // --- flames: burn down, repaint on expiry ---
      for (cy = 0; cy < GH; ++cy)
        for (cx = 0; cx < GW; ++cx) {
          idx = IDX(cx, cy);
          if (flame[idx] && --flame[idx] == 0) mark();
        }

      // --- deaths & win check ---
      alive = 0;
      for (p = 0; p < NUMP; ++p) {
        if (!palive[p]) continue;
        cx = pcx[p]; cy = pcy[p];
        if (flame[IDX(cx, cy)]) { palive[p] = 0; continue; }
        if (pmoving[p]) {
          cx = pcx[p] + DCX[pmdir[p]];
          cy = pcy[p] + DCY[pmdir[p]];
          if (flame[IDX(cx, cy)]) { palive[p] = 0; continue; }
        }
        ++alive;
        winner = p;
      }
      if (alive <= 1) { over = 1; gameframe = OVER_WAIT; if (alive == 0) winner = 255; }
    }

    // --- render players (sprites, drawn over the nametable arena) ---
    spr = 0;
    for (p = 0; p < NUMP; ++p) {
      if (!palive[p]) continue;
      px = ORX + (pcx[p] << 4);
      py = ORY + (pcy[p] << 4);
      if (pmoving[p]) {
        px += DCX[pmdir[p]] * pmoff[p];
        py += DCY[pmdir[p]] * pmoff[p];
      }
      spr = oam_spr(px,     py,     T_PLR0,     p, spr);
      spr = oam_spr(px + 8, py,     T_PLR0 + 1, p, spr);
      spr = oam_spr(px,     py + 8, T_PLR0 + 2, p, spr);
      spr = oam_spr(px + 8, py + 8, T_PLR0 + 3, p, spr);
    }
    oam_hide_rest(spr);

    build_vbuf();
  }
}
